#!/bin/bash
#SBATCH --array=1-1:1
#SBATCH --nice=500
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --requeue
#SBATCH --tmp=32768
#SBATCH -p 3d

HAFARM_VERSION=2.0.0
LAST_FRAME=1
RANGE_FRAME=$[${SLURM_ARRAY_TASK_ID}+1]
if ((${RANGE_FRAME}>${LAST_FRAME})); then RANGE_FRAME=${LAST_FRAME}; fi

OUTPUT_PICTURE=""
echo Job start: `date`
echo Machine name: ${HOSTNAME}
echo User    name: ${USER}
echo Slots:        $NSLOTS
echo Memory stats: `egrep 'Mem|Cache|Swap' /proc/meminfo`
echo Scene file  : /tmp/test1/test2

echo  item3 >>  /tmp/test1/test2
exit_code=$?

echo Render ends: `date`
echo Render target: ""
echo Command was: echo  item3 >>  /tmp/test1/test2
exit $exit_code