#!/bin/bash
#SBATCH --array=1-240:8
#SBATCH --nice=100
#SBATCH -N 1
#SBATCH --exclusive
#SBATCH --requeue
#SBATCH --tmp=32768
#SBATCH -L hbatch_lic:1
#SBATCH --mail-user=s.nazarenko@human-ark.com
#SBATCH -p cuda
#SBATCH -C renders

HAFARM_VERSION=2.0.0
LAST_FRAME=240
RANGE_FRAME=$[${SLURM_ARRAY_TASK_ID}+8]
if ((${RANGE_FRAME}>${LAST_FRAME})); then RANGE_FRAME=${LAST_FRAME}; fi

OUTPUT_PICTURE="/tmp/geo/testRenderSlurm.teapot.1.bgeo.sc"
echo Job start: `date`
echo Machine name: ${HOSTNAME}
echo User    name: ${USER}
echo Slots:        $NSLOTS
echo Memory stats: `egrep 'Mem|Cache|Swap' /proc/meminfo`
echo Scene file  : /tmp/hafarm_slurm_test1_SlurmFilesvVQ7iQ/render/sungrid/jobScript/testRenderSlurm.hip_YYY4_teapot_geometry.hip

/opt/package/rez_packages/houdini/16.5.405/os-CentOS_Linux-7/bin/hython /home/snazarenko/packages/hafarm/2.0.0/py/hafarm/scripts/houdini/harender.py --ignore_tiles -d /out/teapot -f ${SLURM_ARRAY_TASK_ID} ${RANGE_FRAME} -i 1 /tmp/hafarm_slurm_test1_SlurmFilesvVQ7iQ/render/sungrid/jobScript/testRenderSlurm.hip_YYY4_teapot_geometry.hip
exit_code=$?

echo Render ends: `date`
echo Render target: "/tmp/geo/testRenderSlurm.teapot.1.bgeo.sc"
echo Command was: /opt/package/rez_packages/houdini/16.5.405/os-CentOS_Linux-7/bin/hython /home/snazarenko/packages/hafarm/2.0.0/py/hafarm/scripts/houdini/harender.py --ignore_tiles -d /out/teapot -f ${SLURM_ARRAY_TASK_ID} ${RANGE_FRAME} -i 1 /tmp/hafarm_slurm_test1_SlurmFilesvVQ7iQ/render/sungrid/jobScript/testRenderSlurm.hip_YYY4_teapot_geometry.hip
exit $exit_code